ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone    TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio      TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar   TEXT DEFAULT NULL;
